from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

import cv2

from .ollama_client import OllamaVisionClient
from .video_reader import VideoReader
from .video_memory import VideoMemoryStore


MAX_RETRIEVED_SEGMENTS = 12
MAX_EVIDENCE_FRAMES = 4
MAX_DISPLAY_EVIDENCE = 4
VLM_IMAGE_BATCH_SIZE = 2
TEMPORAL_SEGMENT_LIMIT = 2
TEMPORAL_FRAMES_PER_SEGMENT = 2
MIN_STRONG_RETRIEVAL_SCORE = 8.0


def answer_question_over_events(
    events_path: str,
    question: str,
    client: OllamaVisionClient,
    memory_db_path: str | None = None,
) -> str:
    return answer_question_with_evidence(
        events_path,
        question,
        client,
        memory_db_path=memory_db_path,
    )["answer"]


def answer_question_with_evidence(
    events_path: str,
    question: str,
    client: OllamaVisionClient,
    memory_db_path: str | None = None,
) -> dict:
    """Answer through a VSS-like retrieval + visual evidence flow.

    The events JSON is treated as a local debug/export artifact that can point us
    to sampled frames. The answer itself is generated by the VLM from retrieved
    evidence frames whenever possible.
    """

    events_file = Path(events_path)
    events_data = _load_events(events_file)
    current_segments = _segments_from_events(events_data)
    query_plan = _build_query_plan(question)
    retrieved_segments = _retrieve_segments(query_plan, current_segments, memory_db_path)

    root_dir = _infer_root_dir(events_file)
    if query_plan["needs_temporal"]:
        evidence = _collect_temporal_evidence(events_data, retrieved_segments, root_dir, query_plan)
        if not evidence:
            evidence = _collect_evidence_frames(retrieved_segments, root_dir, query_plan)
    else:
        evidence = _collect_evidence_frames(retrieved_segments, root_dir, query_plan)
    if evidence:
        answer = _answer_with_vlm(question, retrieved_segments, evidence, client)
        evidence_payload = _build_evidence_payload(root_dir, evidence)
        if answer:
            result = {
                "answer": _append_evidence_times(answer, evidence_payload),
                "evidence": evidence_payload,
                "retrieval": _build_retrieval_trace(query_plan, retrieved_segments, evidence),
            }
            _write_retrieval_report(root_dir, question, result)
            _log_training_candidate(root_dir, question, result, "vlm_answer")
            return result
        result = {
            "answer": _append_evidence_times(_not_enough_visual_evidence_answer(), evidence_payload),
            "evidence": evidence_payload,
            "retrieval": _build_retrieval_trace(query_plan, retrieved_segments, evidence),
        }
        _write_retrieval_report(root_dir, question, result)
        _log_training_candidate(root_dir, question, result, "not_enough_evidence")
        return result

    if current_segments:
        result = {
            "answer": _not_enough_visual_evidence_answer(),
            "evidence": [],
            "retrieval": _build_retrieval_trace(query_plan, retrieved_segments, evidence),
        }
        _write_retrieval_report(root_dir, question, result)
        _log_training_candidate(root_dir, question, result, "no_evidence")
        return result
    if memory_db_path:
        result = {
            "answer": (
                "Chưa có khoảnh khắc kiểm chứng phù hợp để trả lời. "
                "Hãy nạp video trước, sau đó hỏi lại."
            ),
            "evidence": [],
        }
        _log_training_candidate(root_dir, question, result, "no_evidence")
        return result
    result = {
        "answer": "Chưa có dữ liệu video để trả lời. Hãy nạp video trước.",
        "evidence": [],
    }
    _log_training_candidate(root_dir, question, result, "no_video_data")
    return result


def _load_events(events_file: Path) -> dict | None:
    try:
        data = json.loads(events_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def _log_training_candidate(root_dir: Path, question: str, result: dict, route: str) -> None:
    log_dir = root_dir / "outputs" / "training"
    log_dir.mkdir(parents=True, exist_ok=True)
    record = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "route": route,
        "question": question,
        "model_answer": result.get("answer"),
        "evidence": result.get("evidence") or [],
        "expected_answer": "",
        "review_status": "unreviewed",
    }
    with (log_dir / "qa_candidates.jsonl").open("a", encoding="utf-8") as file:
        file.write(json.dumps(record, ensure_ascii=False) + "\n")


def _write_retrieval_report(root_dir: Path, question: str, result: dict) -> None:
    report_dir = root_dir / "outputs"
    report_dir.mkdir(parents=True, exist_ok=True)
    report = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "question": question,
        "answer": result.get("answer"),
        "retrieval": result.get("retrieval") or {},
        "evidence": result.get("evidence") or [],
    }
    try:
        (report_dir / "retrieval_report.json").write_text(
            json.dumps(report, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    except OSError:
        return


def _build_retrieval_trace(query_plan: dict, segments: list[dict], evidence: list[dict]) -> dict:
    return {
        "intent": {
            "asks_count": query_plan.get("asks_count"),
            "asks_color": query_plan.get("asks_color"),
            "asks_person": query_plan.get("asks_person"),
            "asks_text": query_plan.get("asks_text"),
            "asks_safety": query_plan.get("asks_safety"),
            "needs_temporal": query_plan.get("needs_temporal"),
            "target_objects": sorted(query_plan.get("target_objects") or []),
            "tokens": sorted(query_plan.get("tokens") or []),
        },
        "segments": [
            {
                "segment_id": segment.get("segment_id"),
                "time": f"{segment.get('start_time')}-{segment.get('end_time')}",
                "score": segment.get("_retrieval_score"),
                "reasons": segment.get("_retrieval_reasons") or [],
                "summary": segment.get("summary"),
                "person_count": segment.get("person_count"),
                "risk_level": segment.get("risk_level"),
            }
            for segment in segments[:MAX_RETRIEVED_SEGMENTS]
        ],
        "evidence": [
            {
                "segment_id": item.get("segment_id"),
                "timestamp": item.get("timestamp"),
                "path": item.get("path"),
                "score": item.get("retrieval_score"),
                "reasons": item.get("retrieval_reasons") or [],
                "focus": item.get("focus"),
                "type": item.get("evidence_type") or "representative_frame",
                "motion_score": item.get("motion_score"),
                "motion_label": item.get("motion_label"),
            }
            for item in evidence
        ],
    }


def _segments_from_events(events_data: dict | None) -> list[dict]:
    if not isinstance(events_data, dict):
        return []
    segments = events_data.get("segments") or []
    return [segment for segment in segments if isinstance(segment, dict)]


def _build_query_plan(question: str) -> dict:
    normalized = _normalize_text(question)
    raw_tokens = _raw_question_tokens(normalized)
    tokens = _question_tokens(normalized)
    compact = normalized.replace(" ", "")
    target_objects = _target_objects(normalized, raw_tokens, tokens)
    return {
        "question": question,
        "normalized": normalized,
        "raw_tokens": raw_tokens,
        "tokens": tokens,
        "target_objects": target_objects,
        "asks_count": any(term in normalized for term in ("bao nhieu", "so luong", "dem ", "how many", "count")),
        "asks_color": any(term in normalized for term in ("mau", "color", "mac ao", "ao mau")),
        "asks_person": any(term in tokens for term in ("nguoi", "person", "people", "worker", "staff", "human")),
        "asks_text": any(term in normalized for term in ("chu", "bien", "text", "sign", "doc duoc")),
        "asks_safety": any(term in tokens for term in ("nguyhiem", "unsafe", "danger", "risk", "fight", "violence", "fall")),
        "needs_temporal": _is_temporal_question(question),
        "is_visual": True,
        "compact": compact,
    }


def _target_objects(normalized_question: str, raw_tokens: set[str], tokens: set[str]) -> set[str]:
    if "laptop" in raw_tokens or "notebook" in raw_tokens:
        return {"laptop", "notebook"}
    if "maytinh" in raw_tokens or "computer" in raw_tokens:
        return {"computer", "laptop", "notebook", "monitor"}
    known = {
        "fan": {"quat", "fan", "ventilator"},
        "laptop": {"laptop", "computer", "notebook", "maytinh"},
        "chair": {"ghe", "chair"},
        "desk": {"ban", "desk", "table"},
        "door": {"cua", "door", "entrance"},
        "helmet": {"mu", "helmet"},
        "person": {"nguoi", "person", "people", "worker", "staff"},
    }
    targets = set()
    for canonical, aliases in known.items():
        if tokens.intersection(aliases) or any(alias in normalized_question for alias in aliases):
            targets.add(canonical)
            targets.update(aliases)
    return targets


def _retrieve_segments(
    query_plan: dict,
    current_segments: list[dict],
    memory_db_path: str | None,
) -> list[dict]:
    local_ranked = _rank_segments(current_segments, query_plan)
    memory_ranked = _search_indexed_memory(memory_db_path, query_plan)

    candidates = []
    candidates.extend(local_ranked)
    candidates.extend(memory_ranked)
    candidates.extend(_broad_visual_coverage(current_segments, query_plan))
    return _dedupe_segments(candidates)[:MAX_RETRIEVED_SEGMENTS]


def _answer_with_vlm(
    question: str,
    segments: list[dict],
    evidence: list[dict],
    client: OllamaVisionClient,
) -> str | None:
    structured_answer = _structured_count_answer_from_evidence(question, evidence)
    if structured_answer:
        return structured_answer

    if len(evidence) > VLM_IMAGE_BATCH_SIZE:
        return _answer_with_vlm_chunks(question, segments, evidence, client)

    prompt = _build_vss_qa_prompt(question, segments, evidence)
    response_text = client.analyze_images([item["path"] for item in evidence], prompt)
    parsed = _parse_json_object(response_text)
    if not isinstance(parsed, dict):
        parsed = _retry_plain_visual_answer(question, evidence, client)
    if not isinstance(parsed, dict):
        raw_answer = _clean_user_facing_text(_extract_text_answer(response_text))
        if raw_answer:
            return raw_answer
        return None

    answer = _clean_user_facing_text(str(parsed.get("answer") or "").strip())
    if not answer:
        return None

    confidence = str(parsed.get("confidence") or "unclear").strip()
    evidence_items = parsed.get("evidence")
    limits = _clean_user_facing_text(str(parsed.get("limits") or "").strip())
    if _has_temporal_evidence(evidence):
        answer = _clean_user_facing_text(_replace_static_wording(answer))
        limits = _clean_user_facing_text(_replace_static_wording(limits))

    parts = [answer]
    if isinstance(evidence_items, list) and evidence_items:
        evidence_text = "; ".join(_clean_user_facing_text(str(item)) for item in evidence_items[:4])
        parts.append("Dựa trên: " + evidence_text)
    if limits:
        parts.append("Lưu ý: " + limits)
    return "\n\n".join(parts)


def _answer_with_vlm_chunks(
    question: str,
    segments: list[dict],
    evidence: list[dict],
    client: OllamaVisionClient,
) -> str | None:
    chunk_results = []
    for index in range(0, len(evidence), VLM_IMAGE_BATCH_SIZE):
        chunk = evidence[index : index + VLM_IMAGE_BATCH_SIZE]
        prompt = _build_chunk_qa_prompt(question, chunk)
        response_text = client.analyze_images([item["path"] for item in chunk], prompt)
        parsed = _parse_json_object(response_text)
        if not isinstance(parsed, dict):
            raw_answer = _clean_user_facing_text(_extract_text_answer(response_text))
            if raw_answer:
                parsed = {"answer": raw_answer, "confidence": "unclear", "evidence": []}
        if not isinstance(parsed, dict):
            continue
        answer = _clean_user_facing_text(str(parsed.get("answer") or "").strip())
        if not answer:
            continue
        chunk_results.append(
            {
                "answer": answer,
                "confidence": str(parsed.get("confidence") or "unclear"),
                "evidence": parsed.get("evidence") or [],
                "times": [item.get("timestamp") for item in chunk if item.get("timestamp")],
                "focus": [item.get("focus") for item in chunk if item.get("focus")],
                "indexed_person_counts": [_indexed_person_count(item) for item in chunk],
            }
        )

    if not chunk_results:
        return None

    combined_answer = _summarize_chunk_answers(question, chunk_results, client)
    return _clean_user_facing_text(combined_answer)


def _summarize_chunk_answers(question: str, chunk_results: list[dict], client: OllamaVisionClient) -> str:
    count_answer = _aggregate_count_answer(question, chunk_results)
    if count_answer:
        return count_answer

    prompt = f"""/no_think
Bạn là trợ lý hỏi đáp video. Dưới đây là nhận xét từ nhiều khoảnh khắc đã kiểm tra trong video.
Hãy tổng hợp thành một câu trả lời ngắn gọn, dễ hiểu bằng tiếng Việt.
Không nhắc tới JSON, frame, batch, model hay metadata.

Câu hỏi:
{question}

Nhận xét theo từng nhóm khoảnh khắc:
{json.dumps(chunk_results, ensure_ascii=False)}

Trả về JSON:
{{"answer":"câu trả lời cuối cùng"}}"""
    response_text = client.generate_text(prompt)
    parsed = _parse_json_object(response_text)
    if isinstance(parsed, dict) and str(parsed.get("answer") or "").strip():
        return str(parsed.get("answer")).strip()
    return "; ".join(result["answer"] for result in chunk_results[:4])


def _aggregate_count_answer(question: str, chunk_results: list[dict]) -> str | None:
    plan = _build_query_plan(question)
    if not plan.get("asks_count"):
        return None
    if not plan.get("asks_person"):
        return None

    counts = []
    for result in chunk_results:
        for value in result.get("indexed_person_counts") or []:
            if isinstance(value, int) and value > 0:
                counts.append(value)
    if not counts:
        for result in chunk_results:
            for match in re.findall(r"\b(\d+)\b", str(result.get("answer") or "")):
                value = int(match)
                if 0 < value < 100:
                    counts.append(value)
    if not counts:
        return None

    max_count = max(counts)
    return f"Trong các khoảnh khắc đã kiểm tra, thấy tối đa khoảng {max_count} người."


def _structured_count_answer_from_evidence(question: str, evidence: list[dict]) -> str | None:
    plan = _build_query_plan(question)
    if not (plan.get("asks_count") and plan.get("asks_person")):
        return None
    counts = []
    for item in evidence:
        count = _indexed_person_count(item)
        if isinstance(count, int) and count > 0:
            counts.append(count)
    if not counts:
        return None
    return f"Trong các khoảnh khắc đã kiểm tra, thấy tối đa khoảng {max(counts)} người."


def _indexed_person_count(evidence_item: dict) -> int | None:
    for reason in evidence_item.get("retrieval_reasons") or []:
        match = re.match(r"people:(\d+)$", str(reason))
        if match:
            return int(match.group(1))
    return None


def _combined_confidence(chunk_results: list[dict]) -> str:
    scores = {"low": 1, "medium": 2, "high": 3}
    values = [scores.get(str(item.get("confidence") or "").lower(), 1) for item in chunk_results]
    if not values:
        return "unclear"
    average = sum(values) / len(values)
    if average >= 2.5:
        return "high"
    if average >= 1.6:
        return "medium"
    return "low"


def _not_enough_visual_evidence_answer() -> str:
    return (
        "Tôi chưa đủ bằng chứng hình ảnh để kết luận chắc cho câu hỏi này.\n\n"
        "Dựa trên: các khoảnh khắc đã kiểm tra bên dưới.\n\n"
        "Lưu ý: hệ thống không tự suy diễn khi hình ảnh không đủ rõ."
    )


def _build_chunk_qa_prompt(question: str, evidence: list[dict]) -> str:
    frame_lines = []
    for index, item in enumerate(evidence, start=1):
        frame_lines.append(
            f"{index}. time={item.get('timestamp')}, "
            f"focus={item.get('focus') or 'scene'}, "
            f"motion={item.get('motion_label')}({item.get('motion_score')})"
        )
    return f"""/no_think
Hãy xem các khoảnh khắc video theo đúng thứ tự và trả lời riêng cho nhóm này.
Trả lời tiếng Việt, ngắn gọn, không dùng từ kỹ thuật.

Câu hỏi: {question}

Khoảnh khắc:
{chr(10).join(frame_lines)}

Trả về JSON duy nhất:
{{"answer":"nhận xét từ các khoảnh khắc này","confidence":"low|medium|high","evidence":["thời điểm hoặc dấu hiệu nhìn thấy"]}}"""


def _has_temporal_evidence(evidence: list[dict]) -> bool:
    return any(item.get("evidence_type") == "temporal_sequence" for item in evidence)


def _append_evidence_times(answer: str, evidence_payload: list[dict]) -> str:
    if "Khoảnh khắc đã kiểm tra:" in answer:
        return answer
    times = []
    for item in evidence_payload:
        timestamp = item.get("timestamp")
        if timestamp and timestamp not in times:
            times.append(timestamp)
        if len(times) >= 6:
            break
    if not times:
        return answer
    return answer + "\n\nKhoảnh khắc đã kiểm tra: " + ", ".join(times)


def _build_evidence_payload(root_dir: Path, evidence: list[dict]) -> list[dict]:
    output_dir = root_dir / "outputs" / "evidence"
    output_dir.mkdir(parents=True, exist_ok=True)
    payload = []
    seen = set()
    for index, item in enumerate(evidence[:MAX_DISPLAY_EVIDENCE], start=1):
        source_path = Path(str(item.get("path") or ""))
        if not source_path.exists() or str(source_path) in seen:
            continue
        seen.add(str(source_path))
        annotated_path = output_dir / f"evidence_{index:02d}_{source_path.stem}.jpg"
        _write_annotated_evidence_image(source_path, annotated_path, item, index)
        payload.append(
            {
                "timestamp": item.get("timestamp"),
                "timestamp_sec": item.get("timestamp_sec"),
                "segment_id": item.get("segment_id"),
                "label": _evidence_label(item, index),
                "image_url": _output_url(root_dir, annotated_path),
                "source_url": _output_url(root_dir, source_path),
                "focus": item.get("focus"),
                "retrieval_score": item.get("retrieval_score"),
                "retrieval_reasons": item.get("retrieval_reasons") or [],
                "motion_score": item.get("motion_score"),
                "motion_label": item.get("motion_label"),
            }
        )
    return payload


def _write_annotated_evidence_image(source_path: Path, output_path: Path, item: dict, index: int) -> None:
    image = cv2.imread(str(source_path))
    if image is None:
        return
    height, width = image.shape[:2]
    label = _evidence_label(item, index)
    cv2.rectangle(image, (0, 0), (width - 1, height - 1), (15, 118, 110), 6)
    cv2.rectangle(image, (0, 0), (width, 48), (15, 118, 110), -1)
    cv2.putText(
        image,
        label,
        (14, 32),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.85,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    cv2.imwrite(str(output_path), image)


def _evidence_label(item: dict, index: int) -> str:
    timestamp = item.get("timestamp") or "unknown"
    focus = str(item.get("focus") or "")
    if "fan" in focus:
        return f"Bang chung {index} - {timestamp} - vung quat"
    return f"Bang chung {index} - {timestamp}"


def _output_url(root_dir: Path, path: Path) -> str:
    try:
        relative = path.resolve().relative_to(root_dir.resolve())
    except ValueError:
        return ""
    return "/" + str(relative).replace("\\", "/")


def _replace_static_wording(text: str) -> str:
    if not text:
        return text
    replacements = [
        ("hình ảnh tĩnh này", "chuỗi frame temporal đã sample này"),
        ("khung hình tĩnh này", "chuỗi frame temporal đã sample này"),
        ("ảnh tĩnh này", "chuỗi frame temporal đã sample này"),
        ("hình ảnh tĩnh", "chuỗi frame temporal đã sample"),
        ("khung hình tĩnh", "chuỗi frame temporal đã sample"),
        ("ảnh tĩnh", "chuỗi frame temporal đã sample"),
        ("hình chuỗi frame", "chuỗi frame"),
    ]
    updated = text
    for source, target in replacements:
        updated = updated.replace(source, target)
    return updated


def _clean_user_facing_text(text: str) -> str:
    if not text:
        return text
    replacements = [
        ("chuá»—i frame temporal Ä‘Ã£ sample", "các khoảnh khắc đã trích từ video"),
        ("chuỗi frame temporal đã sample", "các khoảnh khắc đã trích từ video"),
        ("temporal sequence", "các khoảnh khắc đã trích từ video"),
        ("sampled frame sequence", "các khoảnh khắc đã trích từ video"),
        ("sampled frames", "các khoảnh khắc đã trích từ video"),
        ("evidence frames", "các khoảnh khắc đã kiểm tra"),
        ("retrieved evidence frames", "các khoảnh khắc đã kiểm tra"),
        ("frame sequence", "các khoảnh khắc"),
        ("frames", "khoảnh khắc"),
        ("frame", "khoảnh khắc"),
        ("sample", "trích"),
        ("temporal", "theo thời gian"),
        ("metadata", "thông tin phụ"),
        ("JSON", "dữ liệu"),
        ("image_", "ảnh "),
        ("Image ", "Ảnh "),
    ]
    cleaned = text
    for source, target in replacements:
        cleaned = cleaned.replace(source, target)
    cleaned = re.sub(
        r"(?i)khung h[ìi]nh t[ĩi]nh",
        "các khoảnh khắc đã trích từ video",
        cleaned,
    )
    cleaned = re.sub(
        r"(?i)[ảa]nh t[ĩi]nh",
        "các khoảnh khắc đã trích từ video",
        cleaned,
    )
    cleaned = re.sub(
        r"(?i)h[ìi]nh [ảa]nh t[ĩi]nh",
        "các khoảnh khắc đã trích từ video",
        cleaned,
    )
    cleaned = re.sub(r"\bimage[_\s-]*(\d+)\b", r"khoảnh khắc \1", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def _translate_confidence(confidence: str) -> str:
    normalized = confidence.strip().lower()
    if normalized == "high":
        return "cao"
    if normalized == "medium":
        return "trung bình"
    if normalized == "low":
        return "thấp"
    return "chưa rõ"


def _asks_rotation(text: str) -> bool:
    normalized = _normalize_text(text)
    return any(
        term in normalized
        for term in (
            "xoay",
            "quay",
            "dang chay",
            "hoat dong",
            "running",
            "spinning",
            "rotating",
            "turning",
        )
    )


def _build_vss_qa_prompt(question: str, segments: list[dict], evidence: list[dict]) -> str:
    frame_lines = []
    for index, item in enumerate(evidence, start=1):
        motion_hint = ""
        if item.get("evidence_type") == "temporal_sequence":
            motion_hint = (
                f", sequence_index={item.get('sequence_index')}, "
                f"motion={item.get('motion_label')}({item.get('motion_score')}), "
                f"focus={item.get('focus') or 'full_scene'}"
            )
        frame_lines.append(
            f"image_{index}: segment={item.get('segment_id')}, "
            f"time={item.get('timestamp')}, range={item.get('start_time')}-{item.get('end_time')}"
            f"{motion_hint}"
        )

    memory_hints = []
    for segment in segments[:MAX_RETRIEVED_SEGMENTS]:
        memory_hints.append(
            {
                "segment_id": segment.get("segment_id"),
                "time": f"{segment.get('start_time')}-{segment.get('end_time')}",
                "summary": segment.get("summary"),
                "scene": segment.get("scene"),
                "people": segment.get("people"),
                "objects": segment.get("objects"),
                "activities": segment.get("activities"),
                "risk_level": segment.get("risk_level"),
            }
        )

    return f"""/no_think
You are a local video search and summarization assistant, similar to a small NVIDIA VSS-style flow.
Answer the user's question by inspecting the attached evidence frames first.
The memory hints are retrieval metadata only. They are not ground truth and must not override the images.
If frame lines include sequence_index, those images are ordered frames sampled from the original video, not a single static image.

Rules:
- Answer in Vietnamese.
- Use simple words for normal users. Do not mention technical words like frame, sample, temporal, metadata, JSON, image_1, image_2.
- For simple visual questions, try to answer from the visible evidence even if metadata did not name the object.
- For motion/action questions, treat images from the same segment as an ordered short clip. Compare sequence_index values before deciding.
- For fight/fall/chase/pushing questions, decide from posture changes, distance between people, repeated aggressive movement, falling motion, and whether multiple ordered moments support the event.
- Motion score is a rough OpenCV frame-difference hint for the whole frame, not object-specific proof.
- For fan/rotating-object questions, look for blade blur or visible changes across the ordered frames. If the evidence does not prove rotation, say rotation is unclear from the sampled frame sequence.
- For fan questions, the checked moments may be cropped close-ups of the fan area. Use blade blur, changing blade appearance, and oscillating fan-head direction as evidence that a fan is running.
- A fast spinning fan may look like a blurred or translucent circular disk, and may not show obvious position changes between sampled moments. Do not require clear frame-to-frame blade displacement if blade blur is visible.
- If the focus is black_fan_closeup or white_fan_closeup and motion is medium/high across ordered moments, treat that as useful evidence of fan movement unless the images clearly contradict it.
- For counting, count what is visible in the evidence frames. Say if it is an approximate visible-frame count, not a guaranteed unique count across every frame.
- For timing questions, use the frame timestamps/ranges below.
- If evidence is not enough, say what is unclear and what evidence was available.
- Do not claim "not in the video"; say "not visible in the retrieved evidence frames" when uncertain.
- Do not say you only have a static image when sequence_index is present.
- In the final answer, call the checked images "các khoảnh khắc đã kiểm tra".

Frame order:
{chr(10).join(frame_lines)}

Memory hints:
{json.dumps(memory_hints, ensure_ascii=False)}

Question:
{question}

Return compact JSON only:
{{"answer":"Vietnamese answer","evidence":["short evidence with timestamp"],"confidence":"low|medium|high","limits":"short limitation if any"}}
Do not wrap the JSON in markdown."""


def _retry_plain_visual_answer(
    question: str,
    evidence: list[dict],
    client: OllamaVisionClient,
) -> dict | None:
    # Small VLMs sometimes fail JSON when many images are attached. Retry with
    # the first evidence frame to recover a useful answer instead of falling
    # back to hard-coded metadata.
    if not evidence:
        return None
    item = evidence[0]
    prompt = f"""/no_think
Inspect this video evidence frame and answer in Vietnamese.
Frame time: {item.get('timestamp')}, range: {item.get('start_time')}-{item.get('end_time')}.
Question: {question}
Return JSON only:
{{"answer":"Vietnamese answer","evidence":["short evidence"],"confidence":"low|medium|high","limits":"short limitation if any"}}
Do not wrap the JSON in markdown."""
    response_text = client.analyze_images([item["path"]], prompt)
    parsed = _parse_json_object(response_text)
    if isinstance(parsed, dict):
        return parsed
    raw_answer = _extract_text_answer(response_text)
    if raw_answer:
        return {"answer": raw_answer, "confidence": "unclear", "evidence": []}
    return None


def _collect_evidence_frames(segments: list[dict], root_dir: Path, query_plan: dict) -> list[dict]:
    candidates = []
    seen_paths = set()
    for segment_index, segment in enumerate(segments):
        frames = segment.get("sampled_frames") or []
        if not frames and segment.get("frame_paths"):
            frames = [{"path": path} for path in segment.get("frame_paths") or []]

        best_frame = _choose_representative_frame(frames, segment)
        if not best_frame:
            continue
        frame_path = best_frame.get("path")
        if not frame_path:
            continue
        resolved_path = (root_dir / frame_path).resolve()
        if not resolved_path.exists() or str(resolved_path) in seen_paths:
            continue
        seen_paths.add(str(resolved_path))
        score = float(segment.get("_retrieval_score") or 0.0)
        candidates.append(
            {
                "path": str(resolved_path),
                "timestamp": best_frame.get("timestamp") or segment.get("start_time"),
                "timestamp_sec": best_frame.get("timestamp_sec"),
                "segment_id": segment.get("segment_id"),
                "start_time": segment.get("start_time"),
                "end_time": segment.get("end_time"),
                "retrieval_score": score,
                "retrieval_reasons": segment.get("_retrieval_reasons") or [],
                "focus": _question_focus_label(query_plan["question"]),
                "_sort_key": (score, -segment_index),
            }
        )

    candidates.sort(key=lambda item: item["_sort_key"], reverse=True)
    selected = _select_diverse_evidence(candidates)
    for item in selected:
        item.pop("_sort_key", None)
    return selected


def _choose_representative_frame(frames: list[dict], segment: dict) -> dict | None:
    if not frames:
        return None
    start_sec = _parse_time_to_seconds(str(segment.get("start_time") or "0"))
    end_sec = _parse_time_to_seconds(str(segment.get("end_time") or "0"))
    if end_sec <= start_sec:
        return frames[0]
    center = start_sec + (end_sec - start_sec) / 2
    return min(
        frames,
        key=lambda frame: abs(float(frame.get("timestamp_sec") or start_sec) - center),
    )


def _select_diverse_evidence(candidates: list[dict]) -> list[dict]:
    if not candidates:
        return []
    selected = []
    strong = [item for item in candidates if float(item.get("retrieval_score") or 0.0) >= MIN_STRONG_RETRIEVAL_SCORE]
    pool = strong or candidates
    for item in pool:
        if _is_far_enough(item, selected):
            selected.append(item)
        if len(selected) >= MAX_EVIDENCE_FRAMES:
            return selected
    for item in candidates:
        if item not in selected:
            selected.append(item)
        if len(selected) >= MAX_EVIDENCE_FRAMES:
            break
    return selected


def _is_far_enough(item: dict, selected: list[dict]) -> bool:
    timestamp = item.get("timestamp_sec")
    if not isinstance(timestamp, (int, float)):
        return True
    for previous in selected:
        previous_timestamp = previous.get("timestamp_sec")
        if isinstance(previous_timestamp, (int, float)) and abs(float(timestamp) - float(previous_timestamp)) < 1.5:
            return False
    return True


def _collect_temporal_evidence(
    events_data: dict | None,
    segments: list[dict],
    root_dir: Path,
    query_plan: dict,
) -> list[dict]:
    if not isinstance(events_data, dict):
        return []
    video_path = str(events_data.get("video_path") or "").strip()
    if not video_path:
        return []

    resolved_video = (root_dir / video_path).resolve()
    if not resolved_video.exists():
        return []

    output_dir = root_dir / "outputs" / "query_frames"
    output_dir.mkdir(parents=True, exist_ok=True)

    evidence = []
    reader = None
    try:
        reader = VideoReader(str(resolved_video))
        for segment in segments[:TEMPORAL_SEGMENT_LIMIT]:
            start_sec = _segment_start_sec(segment)
            end_sec = _segment_end_sec(segment, reader.duration_seconds)
            timestamps = _temporal_sample_times(start_sec, end_sec, TEMPORAL_FRAMES_PER_SEGMENT)
            segment_evidence = []
            frames_for_motion = []

            for frame_index, timestamp_sec in enumerate(timestamps, start=1):
                ok, frame = reader.read_frame_at(timestamp_sec)
                if not ok or frame is None:
                    continue
                frame_to_save = _crop_motion_focus(frame, query_plan["question"])
                frame_path = output_dir / (
                    f"{Path(video_path).stem}_{segment.get('segment_id')}_"
                    f"motion_{frame_index:02d}.jpg"
                )
                if not cv2.imwrite(str(frame_path), frame_to_save):
                    continue
                frames_for_motion.append(frame_to_save)
                segment_evidence.append(
                    {
                        "path": str(frame_path.resolve()),
                        "timestamp": _format_time(timestamp_sec),
                        "timestamp_sec": timestamp_sec,
                        "segment_id": segment.get("segment_id"),
                        "start_time": segment.get("start_time"),
                        "end_time": segment.get("end_time"),
                        "evidence_type": "temporal_sequence",
                        "focus": _question_focus_label(query_plan["question"]),
                        "sequence_index": frame_index,
                        "retrieval_score": float(segment.get("_retrieval_score") or 0.0),
                        "retrieval_reasons": segment.get("_retrieval_reasons") or [],
                    }
                )

            motion_score = _motion_score(frames_for_motion)
            motion_label = _motion_label(motion_score)
            for item in segment_evidence:
                item["motion_score"] = motion_score
                item["motion_label"] = motion_label
            evidence.extend(segment_evidence)
            if len(evidence) >= MAX_EVIDENCE_FRAMES:
                return evidence[:MAX_EVIDENCE_FRAMES]
    except Exception:
        return evidence
    finally:
        if reader is not None:
            reader.release()

    return evidence[:MAX_EVIDENCE_FRAMES]


def _search_indexed_memory(memory_db_path: str | None, query_plan: dict) -> list[dict]:
    if not memory_db_path:
        return []
    path = Path(memory_db_path)
    if not path.exists():
        return []

    query = " ".join(sorted(query_plan.get("tokens") or []))
    if not query:
        return []

    store = VideoMemoryStore(str(path))
    try:
        results = store.search_segments(query, limit=MAX_RETRIEVED_SEGMENTS)
        ranked = []
        for index, segment in enumerate(results):
            scored = dict(segment)
            score, reasons = _score_segment(scored, query_plan, index)
            scored["_retrieval_score"] = max(score, MIN_STRONG_RETRIEVAL_SCORE / 2)
            scored["_retrieval_reasons"] = ["memory_fts"] + reasons
            ranked.append(scored)
        return ranked
    except Exception:
        return []
    finally:
        store.close()


def _crop_motion_focus(frame, question: str):
    if _is_fan_question(question):
        height, width = frame.shape[:2]
        x1_ratio, y1_ratio, x2_ratio, y2_ratio = _fan_crop_ratios(question)
        y1 = int(height * y1_ratio)
        y2 = int(height * y2_ratio)
        x1 = int(width * x1_ratio)
        x2 = int(width * x2_ratio)
        crop = frame[y1:y2, x1:x2]
        if crop.size:
            return _resize_focus_crop(crop)
    return frame


def _fan_crop_ratios(question: str) -> tuple[float, float, float, float]:
    normalized = _normalize_text(question)
    if any(term in normalized for term in ("den", "black")):
        return 0.58, 0.45, 0.82, 0.76
    if any(term in normalized for term in ("trang", "white")):
        return 0.66, 0.36, 0.88, 0.72
    return 0.50, 0.32, 0.94, 0.90


def _resize_focus_crop(crop):
    height, width = crop.shape[:2]
    target_width = 720
    scale = target_width / max(1, width)
    target_height = max(1, int(height * scale))
    return cv2.resize(crop, (target_width, target_height), interpolation=cv2.INTER_CUBIC)


def _question_focus_label(question: str) -> str:
    if _is_fan_question(question):
        normalized = _normalize_text(question)
        if any(term in normalized for term in ("den", "black")):
            return "black_fan_closeup"
        if any(term in normalized for term in ("trang", "white")):
            return "white_fan_closeup"
        return "fan_area_closeup"
    return "full_scene"


def _is_fan_question(text: str) -> bool:
    normalized = _normalize_text(text)
    return any(term in normalized for term in ("quat", "fan", "ventilator"))


def _rank_segments(segments: list[dict], query_plan: dict) -> list[dict]:
    query_tokens = query_plan.get("tokens") or set()
    if not query_tokens and not query_plan.get("is_visual"):
        return []

    ranked = []
    for index, segment in enumerate(segments):
        score, reasons = _score_segment(segment, query_plan, index)
        if score > 0:
            scored = dict(segment)
            scored["_retrieval_score"] = round(score, 3)
            scored["_retrieval_reasons"] = reasons
            ranked.append((score, -index, scored))
    ranked.sort(reverse=True)
    return [segment for _, _, segment in ranked]


def _score_segment(segment: dict, query_plan: dict, index: int) -> tuple[float, list[str]]:
    text = _segment_text(segment)
    query_tokens = query_plan.get("tokens") or set()
    segment_tokens = set(re.findall(r"[a-z0-9_]+", text))
    overlap = query_tokens.intersection(segment_tokens)
    score = float(len(overlap) * 6)
    reasons = [f"token:{token}" for token in sorted(overlap)[:8]]

    object_text = _normalize_text(_objects_text(segment))
    object_names = [_normalize_text(str(obj.get("name") or "")) for obj in segment.get("objects") or []]
    people_text = _normalize_text(_people_text(segment))
    activities_text = _normalize_text(" ".join(segment.get("activities") or []))
    events_text = _normalize_text(" ".join(str(event.get("description") or "") for event in segment.get("events") or []))

    for raw_token in query_plan.get("raw_tokens") or set():
        if len(raw_token) > 2 and any(raw_token in name for name in object_names):
            score += 35
            reasons.append(f"exact_object:{raw_token}")

    for target in query_plan.get("target_objects") or set():
        if target in object_text:
            score += 22
            reasons.append(f"object:{target}")

    if query_plan.get("asks_person") or (query_plan.get("asks_count") and not query_plan.get("target_objects")):
        person_count = int(segment.get("person_count") or 0)
        if person_count > 0 or segment.get("has_person"):
            score += 12 + min(person_count, 5) * 2
            reasons.append(f"people:{person_count or 'visible'}")

    if query_plan.get("asks_color") and query_plan.get("asks_person") and people_text:
        score += 10
        reasons.append("clothing_color")

    if query_plan.get("needs_temporal"):
        if activities_text:
            score += 8
            reasons.append("activity")
        if events_text:
            score += 8
            reasons.append("event")
        if query_plan.get("asks_person") and (segment.get("has_person") or int(segment.get("person_count") or 0) > 0):
            score += 8
            reasons.append("temporal_people")

    if query_plan.get("asks_safety"):
        risk_level = str(segment.get("risk_level") or "").lower()
        if risk_level in {"warning", "danger", "high"} or segment.get("has_unsafe_behavior"):
            score += 25
            reasons.append(f"risk:{risk_level or 'unsafe'}")
        if any(term in events_text or term in activities_text for term in ("fight", "violence", "fall", "unsafe", "danger")):
            score += 10
            reasons.append("safety_text")

    if score == 0 and query_plan.get("is_visual"):
        score = max(0.1, 1.0 - index * 0.01)
        reasons.append("visual_coverage")
    return score, reasons


def _segment_text(segment: dict) -> str:
    return _normalize_text(
        " ".join(
            [
                str(segment.get("scene") or ""),
                str(segment.get("location") or ""),
                str(segment.get("summary") or ""),
                str(segment.get("searchable_text") or ""),
                " ".join(segment.get("activities") or []),
                " ".join(segment.get("visible_text") or []),
                _objects_text(segment),
                _people_text(segment),
            ]
        )
    )


def _broad_visual_coverage(segments: list[dict], query_plan: dict) -> list[dict]:
    if not segments:
        return []
    scored = []
    for index, segment in enumerate(segments):
        score, reasons = _score_segment(segment, query_plan, index)
        item = dict(segment)
        item["_retrieval_score"] = round(score, 3)
        item["_retrieval_reasons"] = reasons
        scored.append(item)
    scored.sort(key=lambda item: (float(item.get("_retrieval_score") or 0.0), -_segment_start_sec(item)), reverse=True)
    if scored and float(scored[0].get("_retrieval_score") or 0.0) >= MIN_STRONG_RETRIEVAL_SCORE:
        return scored
    return _even_time_coverage(scored)


def _even_time_coverage(scored_segments: list[dict]) -> list[dict]:
    if len(scored_segments) <= MAX_RETRIEVED_SEGMENTS:
        return scored_segments
    ordered = sorted(scored_segments, key=_segment_start_sec)
    step = max(1, len(ordered) // MAX_RETRIEVED_SEGMENTS)
    sampled = ordered[::step][:MAX_RETRIEVED_SEGMENTS]
    remaining = [item for item in scored_segments if item not in sampled]
    return sampled + remaining


def _objects_text(segment: dict) -> str:
    parts = []
    for obj in segment.get("objects") or []:
        parts.append(str(obj.get("name") or ""))
        parts.append(str(obj.get("position") or ""))
        parts.extend(str(item) for item in obj.get("attributes") or [])
    return " ".join(parts)


def _people_text(segment: dict) -> str:
    parts = []
    for person in segment.get("people") or []:
        parts.append(str(person.get("person_label") or ""))
        parts.append(str(person.get("position") or ""))
        parts.extend(str(item) for item in person.get("clothing_colors") or [])
    return " ".join(parts)


def _fallback_from_memory(question: str, segments: list[dict]) -> str:
    ranked = _rank_segments(segments, _build_query_plan(question)) or segments[:MAX_RETRIEVED_SEGMENTS]
    lines = []
    for segment in ranked[:5]:
        lines.append(
            f"- {segment.get('start_time')}-{segment.get('end_time')}: "
            f"{segment.get('summary') or 'khong co summary'}"
        )
    return (
        "Tôi chưa đủ chắc để kết luận từ các khoảnh khắc đã kiểm tra. "
        "Các đoạn liên quan nhất trong video là:\n"
        + "\n".join(lines)
    )


def _dedupe_segments(segments: list[dict]) -> list[dict]:
    deduped = []
    seen = set()
    for segment in segments:
        segment_id = str(segment.get("segment_id") or "")
        frame_key = ""
        frames = segment.get("sampled_frames") or []
        if frames:
            frame_key = str(frames[0].get("path") or "")
        key = (segment_id, frame_key)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(segment)
    return deduped


def _parse_json_object(text: str) -> dict | None:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)
        if not match:
            return None
        try:
            parsed = json.loads(match.group(0))
        except json.JSONDecodeError:
            return None
    return parsed if isinstance(parsed, dict) else None


def _extract_text_answer(text: str) -> str:
    cleaned = text.strip()
    if not cleaned:
        return ""
    if cleaned.startswith("Ollama request failed") or cleaned.startswith("Ollama returned invalid JSON"):
        return ""
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    answer_match = re.search(r'"answer"\s*:\s*"([^"]+)"', cleaned, flags=re.DOTALL)
    if answer_match:
        return answer_match.group(1).strip()
    if cleaned.startswith("{") and cleaned.endswith("}"):
        return ""
    return cleaned[:1200]


def _is_temporal_question(text: str) -> bool:
    normalized = _normalize_text(text)
    temporal_terms = (
        "xoay",
        "quay",
        "chuyen dong",
        "di chuyen",
        "dang chay",
        "hoat dong",
        "running",
        "moving",
        "motion",
        "spinning",
        "rotating",
        "rotate",
        "spin",
        "turning",
        "walking",
        "danh nhau",
        "danh",
        "xay xat",
        "bao luc",
        "hanh hung",
        "tan cong",
        "xung dot",
        "xich mich",
        "xo day",
        "day nga",
        "te nga",
        "nga",
        "roi",
        "rot",
        "duoi",
        "ruot duoi",
        "chay theo",
        "fight",
        "fighting",
        "attack",
        "assault",
        "violence",
        "violent",
        "push",
        "pushing",
        "fall",
        "falling",
        "chase",
        "chasing",
    )
    return any(term in normalized for term in temporal_terms)


def _segment_start_sec(segment: dict) -> float:
    for frame in segment.get("sampled_frames") or []:
        timestamp_sec = frame.get("timestamp_sec")
        if isinstance(timestamp_sec, (int, float)):
            return max(0.0, float(timestamp_sec) - 1.0)
    return _parse_time_to_seconds(str(segment.get("start_time") or "0"))


def _segment_end_sec(segment: dict, duration_seconds: float) -> float:
    parsed = _parse_time_to_seconds(str(segment.get("end_time") or "0"))
    if parsed <= 0:
        parsed = _segment_start_sec(segment) + 2.0
    return min(duration_seconds, max(parsed, _segment_start_sec(segment) + 0.25))


def _parse_time_to_seconds(value: str) -> float:
    parts = value.strip().split(":")
    try:
        if len(parts) == 3:
            hours, minutes, seconds = parts
            return int(hours) * 3600 + int(minutes) * 60 + float(seconds)
        if len(parts) == 2:
            minutes, seconds = parts
            return int(minutes) * 60 + float(seconds)
        return float(value)
    except ValueError:
        return 0.0


def _temporal_sample_times(start_sec: float, end_sec: float, count: int) -> list[float]:
    if count <= 1 or end_sec <= start_sec:
        return [start_sec]
    duration = max(0.2, end_sec - start_sec)
    return [start_sec + duration * index / (count - 1) for index in range(count)]


def _motion_score(frames: list) -> float:
    if len(frames) < 2:
        return 0.0
    scores = []
    previous = None
    for frame in frames:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (160, 90))
        if previous is not None:
            diff = cv2.absdiff(previous, gray)
            scores.append(float(diff.mean()))
        previous = gray
    if not scores:
        return 0.0
    return round(sum(scores) / len(scores), 3)


def _motion_label(score: float) -> str:
    if score >= 12:
        return "high"
    if score >= 4:
        return "medium"
    if score > 0:
        return "low"
    return "unknown"


def _format_time(seconds: float) -> str:
    total_seconds = int(round(seconds))
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


def _question_tokens(text: str) -> set[str]:
    normalized = _normalize_text(text)
    tokens = _raw_question_tokens(normalized)
    stopwords = {
        "co",
        "khong",
        "gi",
        "nao",
        "nhung",
        "cac",
        "trong",
        "video",
        "do",
        "la",
        "o",
        "luc",
        "khi",
        "thoi",
        "diem",
        "bao",
        "nhieu",
        "may",
        "mau",
        "the",
        "a",
        "an",
        "is",
        "are",
        "how",
        "many",
        "what",
        "where",
        "when",
    }
    filtered = {token for token in tokens if len(token) > 1 and token not in stopwords}
    synonyms = {
        "nguoi": {"person", "people", "individual", "staff", "worker", "human"},
        "ao": {"shirt", "clothing", "wearing"},
        "vang": {"yellow", "beige"},
        "trang": {"white"},
        "xanh": {"blue", "green"},
        "den": {"black", "dark"},
        "do": {"red"},
        "quan": {"pants", "trousers"},
        "cam": {"holding", "carrying", "hold"},
        "di": {"walk", "walking", "move", "moving"},
        "gan": {"near", "close"},
        "cua": {"door", "entrance"},
        "laptop": {"laptop", "computer", "notebook"},
        "maytinh": {"computer", "laptop", "monitor"},
        "ban": {"desk", "table"},
        "ghe": {"chair"},
        "chu": {"text", "word", "sign"},
        "quat": {"fan", "ventilator"},
        "xoay": {"spin", "spinning", "rotate", "rotating", "turning"},
        "quay": {"spin", "spinning", "rotate", "rotating", "turning"},
        "chay": {"running", "working", "operating"},
        "hoatdong": {"running", "working", "operating"},
        "chuyendong": {"moving", "motion"},
        "danh": {"fight", "fighting", "attack", "violence"},
        "danhnhau": {"fight", "fighting", "attack", "violence"},
        "baoluc": {"fight", "fighting", "attack", "violence", "violent"},
        "tancong": {"attack", "assault", "violence"},
        "xoday": {"push", "pushing", "shove"},
        "te": {"fall", "falling"},
        "nga": {"fall", "falling"},
        "ruotduoi": {"chase", "chasing", "running"},
        "nguyhiem": {"unsafe", "danger", "hazard", "risk"},
        "ruiro": {"unsafe", "danger", "hazard", "risk"},
        "sukien": {"event", "activity"},
    }
    expanded = set(filtered)
    for token in list(filtered):
        expanded.update(synonyms.get(token, set()))
    return expanded


def _raw_question_tokens(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9_]+", _normalize_text(text)))


def _normalize_text(text: str) -> str:
    text = unicodedata.normalize("NFD", text.lower())
    text = "".join(char for char in text if unicodedata.category(char) != "Mn")
    return text.replace("đ", "d")


def _infer_root_dir(events_file: Path) -> Path:
    resolved = events_file.resolve()
    if resolved.parent.name == "outputs":
        return resolved.parent.parent
    return Path.cwd()


def _normalize_text(text: str) -> str:
    text = unicodedata.normalize("NFD", str(text).lower())
    text = "".join(char for char in text if unicodedata.category(char) != "Mn")
    text = text.replace("đ", "d").replace("Ä‘", "d")
    return re.sub(r"\s+", " ", text).strip()
